version: "3.7"

services:
  # app:
  #   container_name: app
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #     target: dev
  #   ports:
  #     - 8080:8080
  #   environment:
  #     GIN_MODE: debug # release
  #     POSTGRES_URI: postgres://user:password@db:5432/db?sslmode=disable
  #     JWT_SECRET_KEY: jw_secret_key
  #     RESEND_API_KEY: re_123456
  #     NOREPLY_EMAIL: no-reply@example.com
  #     API_HOST_URL: http://127.0.0.1/
  #     APP_HOST_URL: http://127.0.0.1/
  #     PROJECT_NAME: quack-week
  #     OAUTH_GOOGLE_CLIENT_ID: oauth-creds
  #     OAUTH_GOOGLE_SECRET: oauth-creds
  #     OAUTH_GITHUB_CLIENT_ID: oauth-creds
  #     OAUTH_GITHUB_SECRET: oauth-creds
  #     POSTGRES_OPEN_CONNS: 0
  #     POSTGRES_IDLE_CONNS: 2
  #     S3_ACCESS_KEY_ID: S3_ACCESS_KEY_ID
  #     S3_SECRET_ACCESS_KEY: S3_SECRET_ACCESS_KEY
  #     S3_ENDPOINT: br-se1.magaluobjects.com
  #     S3_SECURE: true
  #     S3_BUCKET: quack-week-gopherbase
  #     STRIPE_API_KEY: STRIPE_API_KEY

  db:
    # image: postgres:latest
    image: postgres:16.6-bullseye
    # image: pgvector/pgvector:pg16
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db
    ports:
      - 5432:5432
    expose:
      - 5432
    volumes:
      - postgres_data:/var/lib/postgresql/data

  adminer:
    image: adminer
    ports:
      - 8000:8080

volumes:
  postgres_data:
